CREATE DATABASE IF NOT EXISTS diesel_db;
USE diesel_db;

CREATE TABLE IF NOT EXISTS config (
  id INT(11) NOT NULL DEFAULT 1,
  current_stock DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS nozzle_readings (
  id INT(11) NOT NULL AUTO_INCREMENT,
  reading_date DATE NOT NULL,
  n1_open DECIMAL(10,2) NOT NULL,
  n1_close DECIMAL(10,2) NOT NULL,
  n2_open DECIMAL(10,2) NOT NULL,
  n2_close DECIMAL(10,2) NOT NULL,
  notes TEXT DEFAULT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY (reading_date)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS stock (
  id INT(11) NOT NULL AUTO_INCREMENT,
  add_date DATE NOT NULL,
  liters_added DECIMAL(10,2) NOT NULL,
  notes TEXT DEFAULT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

COMMIT;
